# Generated by Django 2.1 on 2018-10-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mymodelname',
            options={'ordering': ['-my_field_name']},
        ),
    ]
